# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Borneodp < Formula
  desc ""
  homepage "https://github.com/borneodata/homebrew-borneodp"
  version "3.7.0"

  on_macos do
    url "https://github.com/borneodata/homebrew-borneodp/releases/download/v3.7.0/deploy-dataplane_Darwin_all.tar.gz"
    sha256 "d54f0ecbcf6c1abb4aa297a8db0e55b600c55aad8c74f06ff8cab78d6647fdd3"

    def install
      bin.install "deploy-dataplane" => "borneodp"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borneodata/homebrew-borneodp/releases/download/v3.7.0/deploy-dataplane_Linux_arm64.tar.gz"
      sha256 "4b52e6f1b66696424632c18b7a77eedd352bfdddcd38636081983c4fc1f863d2"

      def install
        bin.install "deploy-dataplane" => "borneodp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/borneodata/homebrew-borneodp/releases/download/v3.7.0/deploy-dataplane_Linux_x86_64.tar.gz"
      sha256 "aef1d83666565029ba3b87ffa2e47a3b58a43d10232f4790c1765a8f49a06de6"

      def install
        bin.install "deploy-dataplane" => "borneodp"
      end
    end
  end
end
