# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Borneodp < Formula
  desc ""
  homepage "https://github.com/borneodata/homebrew-borneodp"
  version "3.7.0"

  on_macos do
    url "https://github.com/borneodata/homebrew-borneodp/releases/download/v3.7.0/deploy-dataplane_Darwin_all.tar.gz"
    sha256 "a1883eeee7bdaffc8c0bafbe80852f3ae354f93ee0deee96f75578ec7340ca50"

    def install
      bin.install "deploy-dataplane" => "borneodp"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borneodata/homebrew-borneodp/releases/download/v3.7.0/deploy-dataplane_Linux_arm64.tar.gz"
      sha256 "59d0693bd65a20d9ed52559f77d3750809e2f41ce18e9231a65f105fbc31ce33"

      def install
        bin.install "deploy-dataplane" => "borneodp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/borneodata/homebrew-borneodp/releases/download/v3.7.0/deploy-dataplane_Linux_x86_64.tar.gz"
      sha256 "d6cc936c9617a0bf1eb71195a1b216857d40dcbc2711a3d1adcd039c52722808"

      def install
        bin.install "deploy-dataplane" => "borneodp"
      end
    end
  end
end
